import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body>
        <nav>
          <a href="/">
            HOME
          </a>
          <a href="/campaigns">
            CAMPAIGNS
          </a>
          <a href="/clients">
            CLIENT LISTS
          </a>
        </nav>
        {children}
      </body>
    </html>
  )
}
